project:
  type: website

website:
  title: "Jiwoo Shin"
  description: "AI research notes and paper reviews by Jiwoo Shin"
  site-url: "https://jiwooshin-kr.github.io/blog/"
  image: profile.jpg
  favicon: favicon.png
  open-graph: true
  twitter-card: true
  navbar:
    title: "Notes to Self"
    right:
      - text: Home
        href: index.qmd
      - text: About Me
        href: https://jiwooshin-kr.github.io/
  page-footer:
    left: "© 2026 Jiwoo Shin"

format:
  html:
    respect-user-color-scheme: true
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true
    include-after-body: _goatcounter.html
